POST  http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "nslfkj", 
  "number" : "123"
}

### 
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/61af10e91b6a0f2803ebec0c

### 
PUT http://localhost:3001/api/persons/61b54a293ac8e936224aa211
Content-Type: application/javascript

{
  "name": "neru", 
  "number": "lskf"
}
